# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 19:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rob Cardy', max_length=50)),
                ('username', models.CharField(default='cardy31', max_length=20)),
                ('hashed', models.CharField(default='cheese', max_length=100)),
                ('age', models.IntegerField(default=-1)),
                ('address', models.CharField(default='1 Fake St, Faketown, ON', max_length=70)),
                ('animalToAdopt', models.CharField(default='Dog', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SwipedAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalCode', models.CharField(default='NULL', max_length=50)),
                ('memberUsername', models.CharField(default='cardy31', max_length=20)),
            ],
        ),
    ]
