# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petswipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='hashed',
            new_name='hash',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.AddField(
            model_name='member',
            name='firstname',
            field=models.CharField(default='Rob', max_length=25),
        ),
        migrations.AddField(
            model_name='member',
            name='lastname',
            field=models.CharField(default='Cardy', max_length=25),
        ),
        migrations.AddField(
            model_name='member',
            name='postal',
            field=models.CharField(default='N2B 2W2', max_length=7),
        ),
        migrations.AddField(
            model_name='member',
            name='prov',
            field=models.CharField(default='ON', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(default='1 Fake St, Faketown', max_length=70),
        ),
    ]
